# game directory
starsectorDir=E:/Fractal Softworks/Starsector

# mod_info.json config
modId=starsector-gradle-template
modName=Starsector Gradle Template
modVersion=0.1.0
modAuthor=Your Name
modIsUtility=false
modDescription=A Gradle template for Starsector mods.
modPlugin=org.example.ExampleModPlugin
modJarList=jars/ExampleMod.jar
gameVersion=0.98a-RC8

# build configuration
modFolder=starsector-gradle-template
modOutputJar=ExampleMod.jar
